package frc.robot;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import frc.robot.RobotMap;

public class IO
{  
    // This file contains all gamepad button inputs, axis inputs, and dpad angles.
    // The buttons are to be used in OI, and the axis and dpad inputs are to be used in commands.
    // Do not edit this file, unless the integer values given are wrong.
    
    public final Joystick gamepad = new Joystick(RobotMap.gamepadPort);
  
    public JoystickButton 
        aButton = new JoystickButton(gamepad, 1),
        bButton = new JoystickButton(gamepad, 2),
        xButton = new JoystickButton(gamepad, 3),
        yButton = new JoystickButton(gamepad, 4),
        leftBumperButton = new JoystickButton(gamepad, 5),
        rightBumperButton = new JoystickButton(gamepad, 6),
        backButton = new JoystickButton(gamepad, 7),
        startButton = new JoystickButton(gamepad, 8),
        leftStickButton = new JoystickButton(gamepad, 9),
        rightStickButton = new JoystickButton(gamepad, 10);

    public int getGamepadDpadAngle()
    {
        return gamepad.getPOV();
    }

    public double getGamepadLeftTrigger()
    {
        return gamepad.getRawAxis(2);
    }

    public double getGamepadRightTrigger()
    {
        return gamepad.getRawAxis(3);
    }

    public double getGamepadLeftStickX()
    {
        return gamepad.getRawAxis(0);
    }

    public double getGamepadLeftStickY()
    {
        return gamepad.getRawAxis(1);
    }

    public double getGamepadRightStickX()
    {
        return gamepad.getRawAxis(4);
    }

    public double getGamepadRightStickY()
    {
        return gamepad.getRawAxis(5);
    }
}